// <auto-generated />
namespace EFCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Student_Department_Table_Created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student_Department_Table_Created));
        
        string IMigrationMetadata.Id
        {
            get { return "202302260915506_Student_Department_Table_Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
